// packages/example-vue/src/ThreadChild.vue
<script setup lang="ts">
import type { Thread } from "@b.s/qwery-example-api";
import {
	Card,
	CardContent,
	CardDescription,
	CardFooter,
	CardHeader,
	CardTitle,
} from "./components/ui/card";
import { ref, watch } from "vue";
import { P } from "./components/ui/typography";
import { Button } from "./components/ui/button";
import { Icon } from "@iconify/vue";

const props = defineProps<{
	child: Thread;
	onClickReply: any;
	onClickExpand: any;
}>();

const rerenders = ref(0);

watch(
	() => props.child,
	() => {
		rerenders.value = rerenders.value + 1 * 50;
	},
);

const onClickExpand = props.onClickExpand(props.child);
const onClickReply = props.onClickReply(props.child);
</script>

<template>
	<Card
		class="cursor-pointer border-2"
		:style="{
			borderColor: `hsl(${Math.max(250 - rerenders, 0)}, 100%, 50%)`,
		}">
		<CardHeader>
			<CardTitle>{{ child.createdBy }}</CardTitle>
			<CardDescription class="flex space-x-1">
				<span
					>{{ child.createdAt.toDateString() }} {{ rerenders }}</span
				>
				<span>&middot;</span>
				<span class="inline-flex items-center space-x-1">
					<span>{{ child.likes }}</span>
					<span>
						<Icon icon="radix-icons:star-filled" />
					</span>
				</span>
			</CardDescription>
		</CardHeader>
		<CardContent>
			<P>{{ child.content }}</P>
		</CardContent>
		<CardFooter class="flex-col space-y-4">
			<Button
				v-if="child.children"
				class="w-full"
				variant="secondary"
				@click="onClickExpand">
				View whole thread
			</Button>
			<Button variant="default" class="w-full" @click="onClickReply">
				Reply
			</Button>
		</CardFooter>
	</Card>
</template>

// packages/example-svelte/src/ThreadChild.svelte
<script lang="ts">
	import type { Thread } from "@b.s/qwery-example-api";
	import {
		Card,
		CardContent,
		CardDescription,
		CardFooter,
		CardHeader,
		CardTitle,
	} from "$lib/components/ui/card";
	import { P } from "$lib/components/ui/typography";
	import { Button } from "$lib/components/ui/button";
	import { StarFilled } from "svelte-radix";

	export let child: Thread;
	export let onClickReply: any;
	export let onClickExpand: any;

	let rerenders = 0;

	$: if (child) {
		rerenders = rerenders + 1 * 50;
	}
	$: onExpand = onClickExpand(child);
	$: onReply = onClickReply(child);
</script>

<Card
	class="cursor-pointer border-2"
	style={`border-color: hsl(${Math.max(250 - rerenders, 0)}, 100%, 50%)`}>
	<CardHeader>
		<CardTitle>{child.createdBy}</CardTitle>
		<CardDescription class="flex space-x-1">
			<span>{child.createdAt.toDateString()} {rerenders}</span>
			<span>&middot;</span>
			<span class="inline-flex items-center space-x-1">
				<span>{child.likes}</span>
				<span>
					<StarFilled />
				</span>
			</span>
		</CardDescription>
	</CardHeader>
	<CardContent>
		<P>{child.content}</P>
	</CardContent>
	<CardFooter class="flex-col space-y-4">
		{#if child.children}
			<Button class="w-full" variant="secondary" on:click={onExpand}>
				View whole thread
			</Button>
		{/if}
		<Button variant="default" class="w-full" on:click={onReply}>
			Reply
		</Button>
	</CardFooter>
</Card>
