// src/use-qwery/index.tsx
import React from "react";
import { type CRDT, createCRDT, diff } from "@b.s/incremental";
import { QweryContext } from "../context";
import { useRememberScroll } from "../use-remember-scroll";
import type {
	RefetchableQueryFnParameters,
	UseQweryOptions,
	UseQweryReturn,
} from "./types";

export const useQwery = <
	D extends Record<string | number | symbol, any> =
		| Record<string | number | symbol, any>
		| Array<any>,
	F extends (
		args?: RefetchableQueryFnParameters<D>,
	) => Promise<D> = () => Promise<D>,
	C extends (next: D, previous: D) => unknown = (
		next: D,
		previous: D,
	) => unknown,
	S extends boolean | undefined = false,
>({
	queryKey,
	initialValue,
	onChange,
	onSuccess = noOpFunction,
	onError = noOpFunction,
	subscribe,
	debug = false,
	refetchOnWindowFocus = false,
	broadcast = false,
	suspense = false,
}: UseQweryOptions<D, F, C, S>): S extends true
	? Promise<UseQweryReturn<D>>
	: UseQweryReturn<D> => {
	const [renderCount, setRenderCount] = React.useState(0);
	const context = React.useContext(QweryContext);
	const crdtRef = React.useRef<
		null | undefined | CRDT<D> | Promise<CRDT<D> | undefined>
	>(null);
	const abortControllerRef = React.useRef(new AbortController());

	const proxiedOnChange = new Proxy(onChange, {
		apply: (onChange, thisArg, args) => {
			const result = Reflect.apply(onChange, thisArg, args);

			if (broadcast) {
				const createBroadcastChannel = () => {
					if (broadcast instanceof BroadcastChannel) {
						return broadcast;
					}

					if (!queryKey) {
						return null;
					}

					return new BroadcastChannel(queryKey.toString());
				};

				const channel = createBroadcastChannel();

				channel?.postMessage(diff(args[0], args[1]));
			}

			if (!result) {
				if (queryKey) {
					context?.makeOnChange?.(queryKey).apply(null, [args[0]]);
				}

				setRenderCount(renderCount => renderCount + 1);
			}

			return result;
		},
	});

	const proxiedOnSuccess = new Proxy(onSuccess, {
		apply: (onSuccess, thisArg, args) => {
			Reflect.apply(onSuccess, thisArg, args);

			if (queryKey) {
				context?.makeOnChange?.(queryKey).apply(null, [args[0]]);
			}

			setRenderCount(renderCount => renderCount + 1);
		},
	});

	useRememberScroll();

	React.useEffect(() => {
		const computeInitialValue = async () => {
			const cachedValue = queryKey
				? context?.getCachedValue(queryKey)
				: null;

			if (initialValue instanceof Function) {
				return (await cachedValue) ?? (await initialValue());
			}

			return (await cachedValue) ?? initialValue;
		};

		const initializeCRDT = async () => {
			const initialValue = (await computeInitialValue()) as D;

			if (!initialValue) {
				return;
			}

			const crdt = createCRDT({
				initialValue,
				onChange: proxiedOnChange,
				onSuccess: proxiedOnSuccess,
				onError: onError,
				trackVersions: debug,
			});

			const proxiedDispatch = new Proxy(crdt.dispatch, {
				apply: (dispatch, thisArg, args) => {
					const subscribeOptions = {
						isPersisted: true,
					};

					const result = Reflect.apply(dispatch, thisArg, [
						args[0],
						subscribeOptions,
					]);

					setRenderCount(renderCount => renderCount + 1);

					return result;
				},
			});

			const unsubscribe = subscribe?.(proxiedDispatch);

			if (!suspense) {
				setRenderCount(renderCount => renderCount + 1);
			}

			return { crdt, unsubscribe };
		};

		const setCrdtRef = async (
			initializedCrdt: ReturnType<typeof initializeCRDT>,
		) => {
			crdtRef.current = suspense
				? initializedCrdt.then(result => result?.crdt)
				: (await initializedCrdt)?.crdt;
		};

		const initializedCrdt = initializeCRDT();
		setCrdtRef(initializedCrdt);

		const unsubscribe = async () => {
			const unsubscribe = (await initializedCrdt)?.unsubscribe;

			if (unsubscribe instanceof Promise) {
				return void (await unsubscribe)?.();
			}

			return unsubscribe?.();
		};

		const onWindowFocus = async () => {
			const dispatch = (await initializedCrdt)?.crdt?.dispatch;

			if (!dispatch) {
				return;
			}

			const proxiedDispatch = new Proxy(dispatch, {
				apply: (dispatch, thisArg, args) => {
					const refetchOptions = {
						isPersisted: true,
					};

					const result = Reflect.apply(dispatch, thisArg, [
						args[0],
						refetchOptions,
					]);

					setRenderCount(renderCount => renderCount + 1);

					return result;
				},
			});

			await (initialValue as F)({
				dispatch: proxiedDispatch,
				signal: abortControllerRef.current.signal,
			});
		};

		if (refetchOnWindowFocus) {
			window.addEventListener("focus", onWindowFocus);
		}

		return () => {
			window.removeEventListener("focus", onWindowFocus);
			unsubscribe();
			abortControllerRef.current.abort();
		};
	}, []);

	React.useDebugValue(renderCount);

	const computeInitialValue = () => {
		if (typeof initialValue !== "function") {
			return initialValue;
		}
	};

	if (suspense && crdtRef.current instanceof Promise) {
		return crdtRef.current.then(crdt => ({
			data: crdt?.data ?? computeInitialValue(),
			dispatch: crdt?.dispatch ?? noOpFunction,
			versions: crdt?.versions,
		})) as any;
	}

	const crdt = crdtRef.current as CRDT<D> | undefined;

	return {
		data: crdt?.data ?? computeInitialValue(),
		dispatch: crdt?.dispatch ?? noOpFunction,
		versions: crdt?.versions,
	} as any;
};

const noOpFunction = () => {};

// packages/vue/src/use-qwery/index.tsx
import { createCRDT } from "@b.s/incremental";
import { useQweryContext } from "../context";
import { useRememberScroll } from "../use-remember-scroll";
import type {
	Data,
	InitialValue,
	UseQweryOptions,
	UseQweryReturnWithSuspense,
} from "./types";
import { computed, onMounted, onUnmounted, ref } from "vue";

export const useQwery = <
	I extends InitialValue,
	S extends boolean | undefined = false,
>({
	queryKey,
	initialValue,
	refetch,
	onChange,
	onSuccess = noOpFunction,
	onError = noOpFunction,
	subscribe,
	debug = false,
	refetchOnWindowFocus = false,
	broadcast = false,
	suspense = false,
}: UseQweryOptions<I, S>): UseQweryReturnWithSuspense<I, S> => {
	const context = useQweryContext();
	const data = ref<any>(null);
	const versions = ref<any>(null);
	const dispatch = ref<any>(null);

	const id = Math.random().toString(36).substring(2);
	const abortController = new AbortController();

	const initializeCRDT = async () => {
		const initialValue = await computeInitialValue();

		if (!initialValue) {
			return;
		}

		const crdt = createCRDT({
			initialValue,
			onChange: proxiedOnChange,
			onSuccess: proxiedOnSuccess,
			onError: onError,
			trackVersions: debug,
		});

		const proxiedDispatch = new Proxy(crdt.dispatch, {
			apply: (dispatch, thisArg, args) => {
				const subscribeOptions = {
					isPersisted: true,
				};

				const result = Reflect.apply(dispatch, thisArg, [
					args[0],
					subscribeOptions,
				]);

				return result;
			},
		});

		const unsubscribe = subscribe?.(proxiedDispatch);

		if (!suspense) {
			data.value = crdt.data;
			dispatch.value = crdt.dispatch;
			versions.value = crdt.versions;
		}

		return { crdt, unsubscribe };
	};

	const initializedCrdt = initializeCRDT();

	const createBroadcastChannel = () => {
		if (!queryKey) {
			return null;
		}

		return new BroadcastChannel(queryKey.toString());
	};

	const proxiedOnChange = new Proxy(onChange, {
		apply: (onChange, thisArg, args) => {
			const result = Reflect.apply(onChange, thisArg, args);

			if (broadcast) {
				const channel = createBroadcastChannel();

				channel?.postMessage({
					id,
					next: args[0],
				});
				channel?.close();
			}

			if (!result) {
				if (queryKey) {
					context?.makeOnChange?.(queryKey)(args[0]);
				}

				initializedCrdt.then(result => {
					data.value = result?.crdt.data;
					versions.value = result?.crdt.versions;
				});
			}

			if (suspense && result instanceof Promise) {
				return (result as Promise<unknown>).catch(error => {
					onError(args[0], args[1]);

					throw error;
				});
			}

			return result;
		},
	});

	const proxiedOnSuccess = new Proxy(onSuccess, {
		apply: (onSuccess, thisArg, args) => {
			Reflect.apply(onSuccess, thisArg, args);

			if (queryKey) {
				context?.makeOnChange?.(queryKey)(args[0]);
			}

			initializedCrdt.then(result => {
				data.value = result?.crdt.data;
				versions.value = result?.crdt.versions;
			});
		},
	});

	const computeInitialValue = async () => {
		const cachedValue = queryKey
			? context?.getCachedValue?.(queryKey)
			: null;

		if (initialValue instanceof Function) {
			return (
				(await cachedValue) ??
				(await initialValue(abortController.signal))
			);
		}

		return (await cachedValue) ?? initialValue;
	};

	const unsubscribe = async () => {
		const unsubscribe = (await initializedCrdt)?.unsubscribe;

		if (unsubscribe instanceof Promise) {
			return void (await unsubscribe)?.();
		}

		return unsubscribe?.();
	};

	const channel = createBroadcastChannel();

	const onBroadcast = async (
		event: MessageEvent<{ id: string; next: Data }>,
	) => {
		const crdt = (await initializedCrdt)?.crdt;

		if (event.data.id === id) {
			return;
		}

		// TODO: remove this
		crdt?.dispatch(event.data.next as any, { isPersisted: true });

		data.value = crdt?.data;
	};

	onMounted(() => {
		channel?.addEventListener("message", onBroadcast);
	});

	onUnmounted(() => {
		channel?.removeEventListener("message", onBroadcast);
		channel?.close();
	});

	const onWindowFocus = async () => {
		const crdt = (await initializedCrdt)?.crdt;
		const dispatch = (await initializedCrdt)?.crdt?.dispatch;

		if (!dispatch) {
			return;
		}

		const proxiedDispatch = new Proxy(dispatch, {
			apply: (dispatch, thisArg, args) => {
				const refetchOptions = {
					isPersisted: true,
				};

				const result = Reflect.apply(dispatch, thisArg, [
					args[0],
					refetchOptions,
				]);

				data.value = crdt?.data;

				return result;
			},
		});

		await refetch?.({
			dispatch: proxiedDispatch,
			signal: abortController.signal,
		});
	};

	onMounted(() => {
		if (!refetchOnWindowFocus) {
			return;
		}

		window.addEventListener("focus", onWindowFocus);
	});

	onUnmounted(() => {
		window.removeEventListener("focus", onWindowFocus);
		unsubscribe();
		abortController.abort();
	});

	useRememberScroll();

	if (suspense) {
		return initializedCrdt.then(() => ({
			data: computed(() => data.value ?? computeInitialValue),
			dispatch: computed(() => dispatch.value ?? noOpFunction),
			versions: computed(() => versions.value),
			refetch: refetch ?? noOpFunction,
		})) as any;
	}

	return {
		data: computed(() => data.value ?? computeInitialValue()),
		dispatch: computed(() => dispatch.value ?? noOpFunction),
		versions: computed(() => versions.value),
		refetch: refetch ?? noOpFunction,
	} as any;
};

const noOpFunction = () => {};
